//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog.Admin.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommonResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Blog.Admin.Resources.CommonResources", typeof(CommonResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string 主页 {
            get {
                return ResourceManager.GetString("主页", resourceCulture);
            }
        }
        
        internal static string 文章 {
            get {
                return ResourceManager.GetString("文章", resourceCulture);
            }
        }
        
        internal static string 话题 {
            get {
                return ResourceManager.GetString("话题", resourceCulture);
            }
        }
        
        internal static string 类别 {
            get {
                return ResourceManager.GetString("类别", resourceCulture);
            }
        }
        
        internal static string 联系方式 {
            get {
                return ResourceManager.GetString("联系方式", resourceCulture);
            }
        }
        
        internal static string 设置 {
            get {
                return ResourceManager.GetString("设置", resourceCulture);
            }
        }
        
        internal static string 域 {
            get {
                return ResourceManager.GetString("域", resourceCulture);
            }
        }
        
        internal static string 注销 {
            get {
                return ResourceManager.GetString("注销", resourceCulture);
            }
        }
        
        internal static string 登录 {
            get {
                return ResourceManager.GetString("登录", resourceCulture);
            }
        }
        
        internal static string 注册 {
            get {
                return ResourceManager.GetString("注册", resourceCulture);
            }
        }
        
        internal static string 未设置昵称 {
            get {
                return ResourceManager.GetString("未设置昵称", resourceCulture);
            }
        }
        
        internal static string 未设置邮箱 {
            get {
                return ResourceManager.GetString("未设置邮箱", resourceCulture);
            }
        }
        
        internal static string 搜索 {
            get {
                return ResourceManager.GetString("搜索", resourceCulture);
            }
        }
        
        internal static string 创建 {
            get {
                return ResourceManager.GetString("创建", resourceCulture);
            }
        }
        
        internal static string 名称 {
            get {
                return ResourceManager.GetString("名称", resourceCulture);
            }
        }
        
        internal static string 键 {
            get {
                return ResourceManager.GetString("键", resourceCulture);
            }
        }
        
        internal static string 标题 {
            get {
                return ResourceManager.GetString("标题", resourceCulture);
            }
        }
        
        internal static string 公开 {
            get {
                return ResourceManager.GetString("公开", resourceCulture);
            }
        }
        
        internal static string 是 {
            get {
                return ResourceManager.GetString("是", resourceCulture);
            }
        }
        
        internal static string 否 {
            get {
                return ResourceManager.GetString("否", resourceCulture);
            }
        }
        
        internal static string 编辑 {
            get {
                return ResourceManager.GetString("编辑", resourceCulture);
            }
        }
        
        internal static string 删除 {
            get {
                return ResourceManager.GetString("删除", resourceCulture);
            }
        }
        
        internal static string 副标题 {
            get {
                return ResourceManager.GetString("副标题", resourceCulture);
            }
        }
        
        internal static string 识别链接 {
            get {
                return ResourceManager.GetString("识别链接", resourceCulture);
            }
        }
        
        internal static string 封面图片 {
            get {
                return ResourceManager.GetString("封面图片", resourceCulture);
            }
        }
        
        internal static string 语言 {
            get {
                return ResourceManager.GetString("语言", resourceCulture);
            }
        }
        
        internal static string 创建副本 {
            get {
                return ResourceManager.GetString("创建副本", resourceCulture);
            }
        }
        
        internal static string 转换为图片块 {
            get {
                return ResourceManager.GetString("转换为图片块", resourceCulture);
            }
        }
        
        internal static string 转换为文本块 {
            get {
                return ResourceManager.GetString("转换为文本块", resourceCulture);
            }
        }
        
        internal static string 提交 {
            get {
                return ResourceManager.GetString("提交", resourceCulture);
            }
        }
        
        internal static string 状态 {
            get {
                return ResourceManager.GetString("状态", resourceCulture);
            }
        }
        
        internal static string 取消 {
            get {
                return ResourceManager.GetString("取消", resourceCulture);
            }
        }
        
        internal static string 默认 {
            get {
                return ResourceManager.GetString("默认", resourceCulture);
            }
        }
        
        internal static string 选择 {
            get {
                return ResourceManager.GetString("选择", resourceCulture);
            }
        }
        
        internal static string 内容管理 {
            get {
                return ResourceManager.GetString("内容管理", resourceCulture);
            }
        }
        
        internal static string 域管理 {
            get {
                return ResourceManager.GetString("域管理", resourceCulture);
            }
        }
        
        internal static string 用户设置 {
            get {
                return ResourceManager.GetString("用户设置", resourceCulture);
            }
        }
        
        internal static string 变更 {
            get {
                return ResourceManager.GetString("变更", resourceCulture);
            }
        }
        
        internal static string 返回 {
            get {
                return ResourceManager.GetString("返回", resourceCulture);
            }
        }
        
        internal static string 新增域 {
            get {
                return ResourceManager.GetString("新增域", resourceCulture);
            }
        }
        
        internal static string 编辑类别 {
            get {
                return ResourceManager.GetString("编辑类别", resourceCulture);
            }
        }
        
        internal static string 新增类别 {
            get {
                return ResourceManager.GetString("新增类别", resourceCulture);
            }
        }
        
        internal static string 新增话题 {
            get {
                return ResourceManager.GetString("新增话题", resourceCulture);
            }
        }
        
        internal static string 编辑话题 {
            get {
                return ResourceManager.GetString("编辑话题", resourceCulture);
            }
        }
        
        internal static string 创建文章 {
            get {
                return ResourceManager.GetString("创建文章", resourceCulture);
            }
        }
        
        internal static string 编辑文章 {
            get {
                return ResourceManager.GetString("编辑文章", resourceCulture);
            }
        }
        
        internal static string 一般 {
            get {
                return ResourceManager.GetString("一般", resourceCulture);
            }
        }
        
        internal static string 社交账号链接 {
            get {
                return ResourceManager.GetString("社交账号链接", resourceCulture);
            }
        }
        
        internal static string 网站地图 {
            get {
                return ResourceManager.GetString("网站地图", resourceCulture);
            }
        }
        
        internal static string 更新 {
            get {
                return ResourceManager.GetString("更新", resourceCulture);
            }
        }
        
        internal static string 翻译 {
            get {
                return ResourceManager.GetString("翻译", resourceCulture);
            }
        }
        
        internal static string 新增链接 {
            get {
                return ResourceManager.GetString("新增链接", resourceCulture);
            }
        }
        
        internal static string 新增区块 {
            get {
                return ResourceManager.GetString("新增区块", resourceCulture);
            }
        }
        
        internal static string ___选择语言___ {
            get {
                return ResourceManager.GetString("-- 选择语言 --", resourceCulture);
            }
        }
        
        internal static string 中文 {
            get {
                return ResourceManager.GetString("中文", resourceCulture);
            }
        }
        
        internal static string 英语 {
            get {
                return ResourceManager.GetString("英语", resourceCulture);
            }
        }
        
        internal static string 日语 {
            get {
                return ResourceManager.GetString("日语", resourceCulture);
            }
        }
        
        internal static string 创建网站地图 {
            get {
                return ResourceManager.GetString("创建网站地图", resourceCulture);
            }
        }
        
        internal static string 创建翻译 {
            get {
                return ResourceManager.GetString("创建翻译", resourceCulture);
            }
        }
    }
}
